readrate/books/urls.py
from django.urls import path
from .views import BooksSearchView, BooksListView, BooksInformationView

app_name = "books"
urlpatterns = [
    path("", BooksListView.as_view(), name="index"),
    path("search", BooksSearchView.as_view(), name="search"),
    path("books/<slug:slug>/", BooksInformationView.as_view(), name="info"),
]

readrate/readrate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('books/', include('books.urls')),
    path('', include('users.urls')),
    path('main/', include('mainpages.urls')),
    
    # Path to connect the search field to the book app
    path("books/", include("books.urls")),
]

readrate/books/models.py
from django.db import models, IntegrityError
from django.contrib.auth.models import User
from django.utils.text import slugify

class Genero(models.Model):
    nome = models.CharField(max_length=256, unique=True)
    
    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        self.nome = self.nome.title()
        super().save(*args, **kwargs)
    
class Autor(models.Model):
    nome = models.CharField(max_length=256, unique=True)
    
    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        self.nome = self.nome.title()
        super().save(*args, **kwargs)
class Livro(models.Model):
    titulo = models.CharField(max_length=256)
    slug = models.CharField(max_length=256, blank=True)
    numero_paginas = models.IntegerField()
    autores = models.ManyToManyField(Autor)
    generos = models.ManyToManyField(Genero)
    
    def __str__(self):
        return self.titulo
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        super().save(*args, **kwargs)

class Nota(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)
    nota = models.IntegerField()

class Favorito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)

readrate/books/views.py
from django.db import IntegrityError
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.conf import settings
from .models import Livro, Genero, Autor
import requests

# Create your views here.

class BooksListView(ListView):
    model = Livro
    paginate_by = 100
    template_name = "books/index.html"
    ordering = "-id"
    
class BooksSearchView(ListView):
    model = Livro
    paginate_by = 100
    template_name = "books/books_list.html"
    context_object_name = "query"
    ordering = "-id"
    
    def _search_books(self, search_query):
        base_url = "https://www.googleapis.com/books/v1/volumes"
        params = {
            "q": search_query,
            "key": settings.SECRET_KEY,
            "maxResults": 40
        }
        
        try:
            response = requests.get(base_url, params=params)
            if response.status_code == 200:
                return response.json().get("items", [])
        except Exception as e:
            print(f"Error searching books: {e}")
        return []
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("q").strip()
        context["search"] = search.capitalize()
        
        book_queryset = Livro.objects.filter(titulo__icontains=search).order_by("-id")
        context["books"] = book_queryset
        
        return context
    
    def get_queryset(self):
        search = self.request.GET.get("q").strip()
        
        if search:
            api_data = self._search_books(search)
            
            for item in api_data:
                volume_info = item.get("volumeInfo", {})
                title = volume_info.get("title", "N/A")
                
                if Livro.objects.filter(Q(titulo__icontains=title)).exists():
                    continue
                
                pageCount = volume_info.get("pageCount", "N/A")
                authors_list = volume_info.get("authors", ["N/A"])
                genres_list = volume_info.get("categories", ["N/A"])
                
                book = Livro.objects.create(
                    titulo=title,
                    numero_paginas=pageCount,
                )
                
                for author_name in authors_list:
                    existing_authors = Autor.objects.filter(nome__icontains=author_name)
                    
                    if existing_authors.exists():
                        for existing_author in existing_authors:
                            book.autores.add(existing_author)
                    else:
                        new_author = Autor.objects.create(nome=author_name)
                        book.autores.add(new_author)
                        
                for genre_name in genres_list:
                    existing_genres = Genero.objects.filter(nome__icontains=genre_name)
                    
                    if existing_genres.exists():
                        for existing_genre in existing_genres:
                            book.generos.add(existing_genre)
                    else:
                        new_genre = Genero.objects.create(nome=genre_name)
                        book.generos.add(new_genre)
                        
            return Livro.objects.filter(titulo__icontains=search).order_by("-id")
class BooksInformationView(DetailView):
    model = Livro
    template_name = "books/book_info.html"

readrate/books/templates/books/book_info.html
<h1>Book detail</h1>

readrate/books/templates/books/books_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pesquisa{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row my-3">
            <div class="col">
                <h2>Resultados da pesquisa: <span class="fw-normal  text-primary">{{ search }}</span></h2>
                
            </div>
        </div>

        <div class="row my-3">
            {% if books %}
                <div class="container">
                    <div class="row">
                        <div class="col">
                            {% for book in books %}
                                <ul class="list-group mb-3">
                                    {% comment %} Title {% endcomment %}
                                    <li class="list-group-item list-group-item-dark">
                                        <a href="{% url "books:info" slug=book.slug %}" class="link-dark link-underline-opacity-0 link-underline-opacity-75-hover">
                                            <h3 class="fs-5">{{ book.titulo }}</h3>
                                        </a>
                                    </li>
                                    
                                    {% comment %} Book thumbnail {% endcomment %}
                                    <li class="list-group-item">
                                        <a href="{% url "books:info" slug=book.slug %}" class="link-dark link-underline-opacity-0 link-underline-opacity-75-hover">
                                            <img src="https://via.placeholder.com/150x250" class="img-fluid rounded float-start mt-2 ms-2">
                                        </a>

                                        {% comment %} Data content {% endcomment %}
                                        <ul class="list-group">
                                            {% comment %} Authors {% endcomment %}
                                            <li class="list-group-item d-flex mx-3">
                                                {% if book.autores.all|length > 1 %}
                                                <h4 class="fs-6">Autores: </h4>
                                                {% else %}
                                                    <h4 class="fs-6">Autor: </h4>
                                                {% endif %}
                                                
                                                {% for autor in book.autores.all %}
                                                    {% if forloop.last %}
                                                        <div class="mx-1">
                                                            {{ autor }}.
                                                        </div>
                                                    {% else %}
                                                        <div class="mx-1">
                                                            {{ autor }}, 
                                                        </div>
                                                    {% endif %}
                                                    
                                                {% endfor %}
                                            </li>

                                            {% comment %} Genres {% endcomment %}
                                            <li class="list-group-item d-flex mx-3">
                                                {% if book.generos.all|length > 1 %}
                                                <h4 class="fs-6">Gêneros: </h4>
                                                {% else %}
                                                    <h4 class="fs-6">Gênero: </h4>
                                                {% endif %}
                                                
                                                {% for genre in book.generos.all %}
                                                    {% if forloop.last %}
                                                        <div class="mx-1">
                                                            {{ genre }}.
                                                        </div>
                                                    {% else %}
                                                        <div class="mx-1">
                                                            {{ genre }}, 
                                                        </div>
                                                    {% endif %}
                                                    
                                                {% endfor %}
                                            </li>

                                            {% comment %} Page count {% endcomment %}
                                            <li class="list-group-item d-flex mx-3">
                                                <h4 class="fs-6">Páginas: </h4>
                                                <div class="mx-1">
                                                    {{ book.numero_paginas }}
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                </ul>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                Sentimos muito, nenhum livro com estes parâmetros foi encontrado.
            {% endif %}
        </div>
    </div>
{% endblock content %}

readrate/books/templates/books/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Livros{% endblock title %}

readrate/books/templates/books/showbook.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{book.titulo}}
{% endblock %}

{% block content %}


<div class="container mt-3">
    <div class="row mb-3">
        <div class="col-12">
            <h2 class="mb-3">{{book.titulo}}</h2>
            <p>{{ book.descricao }}</p>
            <img src="{{ book.imagem.url }}" alt="{{ book.titulo }}">
        </div>
    </div>
</div>

{% endblock  %}